export const iconMap = {
  health: '/icons/icon_health.png',
  sanity: '/icons/icon_sanity.png',
  hunger: '/icons/icon_hunger.png',
  soul: '/icons/icon_soul.png',
  beast: '/icons/icon_mem_beast_mode.png',
  ghost: '/icons/icon_mem_ghost_mode.png',
  collar: '/icons/icon_mem_xq.png',
  'collar-lv2': '/icons/icon_mem_xq_lv2.png',
  'collar-lv3': '/icons/icon_mem_xq_lv3.png',
  'collar-lv4-an': '/icons/icon_mem_xq_lv4_an.png',
  'collar-lv4-yue': '/icons/icon_mem_xq_lv4_yue.png',
  repair: '/icons/icon_mem_repair.png',
  hlxz: '/icons/icon_mem_hlxz.png',
  mb: '/icons/icon_mem_mb.png',
  'food-lbnh': '/icons/icon_mem_food_lbnh.png',
  'food-hsmz': '/icons/icon_mem_food_hsmz.png',
  'food-kqm': '/icons/icon_mem_food_kqm.png',
  'food-rxxcd': '/icons/icon_mem_food_rxxcd.png',
  'food-xqs': '/icons/icon_mem_food_xqs.png',
  yue: '/icons/icon_mem_yue.png',
  shadowmem: '/icons/icon_shadowmem.png',
  shadowmem_minion: '/icons/icon_shadowmem_minion.png',
  'yue-pet': '/icons/icon_mem_yue_pet.png',
  'shadowmem-pet': '/icons/icon_shadowmem_pet.png',
  'shadowmem_minion_pet': '/icons/icon_shadowmem_minion_pet.png',
  'yue-bond': '/icons/icon_mem_yue_bond.png',
  'shadowmem-bond': '/icons/icon_shadowmem_bond.png',
  qjdxy: '/icons/icon_mem_qjdxy.png',
  'tomb-upgrader': '/icons/icon_mem_tomb_upgrader.png',
  corpse: '/icons/icon_mem_corpse.png',
  'shadow-gestalt': '/icons/icon_mem_shadow_gestalt.png',
  soul_wall: '/icons/icon_soul_wall.png',
  dj: '/icons/icon_dj.png',
  djhm: '/icons/icon_djhm.png',
  kyxt: '/icons/icon_kyxt.png',
  hpky: '/icons/icon_hpky.png',
  ghost_fire: '/icons/icon_ghost_fire.png',
  spoil: '/icons/icon_spoil.png',
  mem_corpse_site: '/icons/icon_mem_corpse_site.png',
  ftxd: '/icons/icon_ftxd.png',
  moonaligned: '/icons/icon_moonaligned.png',
  shadowaligned: '/icons/icon_shadowaligned.png',
  tenkibeam: '/icons/icon_tenki_beam.png',
  yuebeam: '/icons/icon_yuebeam.png',
  trap: '/icons/icon_trap.png',
  mem_gestalt_guard: '/icons/icon_mem_gestalt_guard.png',
  stalker_minion: '/icons/icon_stalker_minion.png',
  atk: '/icons/icon_damage.png',
  state: '/icons/icon_state.png',
  shadowseer: '/icons/icon_shadowseer.png',
  command: '/icons/icon_command.png',
  shadowmem_pet_body: '/shadowmem_pet_body.png',
  mem_ruinsnightmare: '/mem_ruinsnightmare.png',




  mod: '/icons/icon_mod.png',
  original: '/icons/icon_original.png',
}

// HSL 颜色配置：h (色相), s (饱和度%), l (亮度%)
export const colorMap = {
  health: { h: 0, s: 100, l: 65 },
  sanity: { h: 48, s: 100, l: 60 },
  hunger: { h: 30, s: 100, l: 60 },
  soul: { h: 275, s: 96, l: 75 },
  beast: { h: 46, s: 90, l: 47 },
  ghost: { h: 215, s: 25, l: 65 },
  collar: { h: 189, s: 94, l: 37 },
  'collar-lv2': { h: 189, s: 94, l: 37 },
  'collar-lv3': { h: 189, s: 94, l: 37 },
  'collar-lv4-an': { h: 189, s: 94, l: 37 },
  'collar-lv4-yue': { h: 189, s: 94, l: 37 },
  repair: { h: 142, s: 71, l: 45 },
  hlxz: { h: 25, s: 50, l: 50 },
  mb: { h: 0, s: 0, l: 65 },
  'food-lbnh': { h: 190, s: 70, l: 60 },
  'food-hsmz': { h: 15, s: 80, l: 55 },
  'food-kqm': { h: 35, s: 85, l: 50 },
  'food-rxxcd': { h: 0, s: 85, l: 45 },
  'food-xqs': { h: 45, s: 90, l: 55 },
  yue: { h: 217, s: 55, l: 54 },
  'yue-pet': { h: 195, s: 90, l: 75 },
  'yue-bond': { h: 195, s: 90, l: 75 },
  shadowmem: { h: 280, s: 60, l: 50 },
  shadowmem_minion: { h: 0, s: 0, l: 0 },
  'shadowmem-pet': { h: 280, s: 60, l: 50 },
  shadowmem_minion_pet: { h: 200, s: 2, l: 24 },
  'shadowmem-bond': { h: 280, s: 60, l: 50 },
  qjdxy: { h: 260, s: 30, l: 45 },
  'tomb-upgrader': { h: 258, s: 90, l: 66 },
  corpse: { h: 0, s: 0, l: 55 },
  'shadow-gestalt': { h: 270, s: 50, l: 45 },
  soul_wall: { h: 275, s: 96, l: 75 },
  dj: { h: 340, s: 60, l: 50 },
  djhm: { h: 20, s: 80, l: 50 },
  kyxt: { h: 280, s: 70, l: 60 },
  hpky: { h: 300, s: 80, l: 70 },
  ghost_fire: { h: 180, s: 70, l: 60 },
  spoil: { h: 100, s: 50, l: 40 },
  mem_corpse_site: { h: 30, s: 40, l: 45 },
  ftxd: { h: 0, s: 0, l: 0 },
  moonaligned: { h: 189, s: 97, l: 63 },
  shadowaligned: { h: 358, s: 53, l: 22 },
  shadowseer: { h: 358, s: 53, l: 22 },
  tenkibeam: { h: 228, s: 100, l: 54 },
  yuebeam: { h: 237, s: 100, l: 90 },
  trap: { h: 117, s: 51, l: 82 },
  mem_gestalt_guard: { h: 154, s: 20, l: 47 },
  stalker_minion: { h: 13, s: 17, l: 33 },
  atk: { h: 49, s: 8, l: 59 },
  state: { h: 50, s: 93, l: 60 },
  command: { h: 240, s: 67, l: 72 },
  shadowmem_pet_body: { h: 0, s: 1, l: 36 },
  mem_ruinsnightmare: { h: 358, s: 53, l: 22 },


  mod: { h: 199, s: 92, l: 60 },
  original: { h: 40, s: 54, l: 52 },
}
