export const nounMap = {
  '生命值': 'health',
  '饱食度': 'hunger',
  '理智值': 'sanity',
  '精神值': 'sanity',
  '灵魂值': 'soul',
  '灵魂值系统': 'soul',
  '灵魂池': 'hpky',
  '兽化': 'beast',
  '怨灵': 'ghost',
  '尸体': 'corpse',
  '芒头': 'corpse',
  '芒身': 'corpse',
  '芒手': 'corpse',
  '芒腿': 'corpse',
  '芒芒的尸体': 'corpse',
  '封印项圈': 'collar',
  '封印项圈lv1': 'collar',
  '封印项圈lv2': 'collar-lv2',
  '封印项圈lv3': 'collar-lv3',
  '封印项圈lv4·暗': 'collar-lv4-an',
  '暗项圈': 'collar-lv4-an',
  '封印项圈lv4·月': 'collar-lv4-yue',
  '月项圈': 'collar-lv4-yue',
  '芒式修补工具': 'repair',
  '狐狸的凶宅': 'hlxz',
  '芒芒的坟墓': 'mb',
  '芒芒的墓碑': 'mb',
  '凉拌脑花': 'food-lbnh',
  '红烧芒肘': 'food-hsmz',
  '烤全芒': 'food-kqm',
  '热心肠血冻': 'food-rxxcd',
  '星期四特惠套餐': 'food-xqs',
  '芒伊月': 'yue',
  '荒尹沐': 'shadowmem',
  '友善的芒伊月': 'mem_yue_pet',
  '友善的荒尹沐': 'shadowmem_pet',
  '光辉意志': 'mem_yue_bond',
  '先驱意志': 'shadowmem_bond',
  '被囚禁的虚影': 'qjdxy',
  '被侵蚀的虚影': 'shadow-gestalt',
  '尸体防腐核心': 'tomb-upgrader',
  '芒芒尸体的设计图': 'mem_corpse_site',
  '魂墙(物品)': 'soul_wall',
  '电锯惊魂': 'dj',
  '刻印形态': 'kyxt',
  '电锯轰鸣': "djhm",
  '魂魄刻印': "state",
  '沐尹荒': 'shadowmem_minion',
  '友善的沐尹荒': 'shadowmem_minion_pet',
  '身体(友善的荒尹沐)': 'shadowmem_pet_body',
  '编织梦魇': 'stalker_minion',
  '位面寄生': 'shadowaligned',
  '位面能量': 'shadowaligned',
  '暗影位面寄生': 'shadowaligned',
  '月亮位面寄生': 'moonaligned',
  '位面封锁': 'moonaligned',
  '敌意虚影·启迪': 'mem_gestalt_guard',
  '闪耀刻印': 'state',
  '鬼火': 'ghost_fire',
  '月光灼烧': 'state',
  '位面实体降格': 'state',
  '芒伊木': 'mod',
  '芒芒的肢体': 'corpse',
  '灵魂实体专精': 'mod',
  '彼世的光芒': 'mod',
  '死体精通': 'mod',
  '启迪陷阱空投仓': 'trap',
  '启迪陷阱': 'trap',
  '启迪陷阱空袭': 'trap',
  '启迪陷阱阵列': 'trap',
  '再一次的机会': 'state',
  '复生虚弱': 'state',
  '灵魂震荡': 'state',
  '灵魂裂痕': 'state',
  '捕猎姿态': 'beast',
  '分头行动': 'ftxd',
  '意识转移': 'ftxd',
  '死亡回归': 'mod',
  '友善随从': 'mod',
  '天基激光': 'tenkibeam',
  '月能激光': 'yuebeam',
  '月能灼烧伤害': 'original',
  '极限催眠': 'original',
  '虚影轰炸区': 'atk',
  '三连击': 'atk',
  '跳劈': 'atk',
  '横扫': 'atk',
  '冲刺': 'atk',
  '劈砍': 'atk',
  '暗影观察者': 'shadowseer',
  '收回': 'command',
  '战斗': 'command',
  '工作命令': 'command',
  '解散': 'command',
  '汇合行动(解散)': 'command',
  '分头行动(友善的荒尹沐)': 'command',
  '潜伏恐惧': 'mem_ruinsnightmare',
  '腐烂时间': 'spoil',
  '腐烂速率': 'spoil',
};

export const iconMap = {
  health: '/icons/icon_health.png',
  sanity: '/icons/icon_sanity.png',
  hunger: '/icons/icon_hunger.png',
  soul: '/icons/icon_soul.png',
  beast: '/icons/icon_mem_beast_mode.png',
  ghost: '/icons/icon_mem_ghost_mode.png',
  collar: '/icons/icon_mem_xq.png',
  'collar-lv2': '/icons/icon_mem_xq_lv2.png',
  'collar-lv3': '/icons/icon_mem_xq_lv3.png',
  'collar-lv4-an': '/icons/icon_mem_xq_lv4_an.png',
  'collar-lv4-yue': '/icons/icon_mem_xq_lv4_yue.png',
  repair: '/icons/icon_mem_repair.png',
  hlxz: '/icons/icon_mem_hlxz.png',
  mb: '/icons/icon_mem_mb.png',
  'food-lbnh': '/icons/icon_mem_food_lbnh.png',
  'food-hsmz': '/icons/icon_mem_food_hsmz.png',
  'food-kqm': '/icons/icon_mem_food_kqm.png',
  'food-rxxcd': '/icons/icon_mem_food_rxxcd.png',
  'food-xqs': '/icons/icon_mem_food_xqs.png',
  yue: '/icons/icon_mem_yue.png',
  shadowmem: '/icons/icon_shadowmem.png',
  shadowmem_minion: '/icons/icon_shadowmem_minion.png',
  'mem_yue_pet': '/icons/icon_mem_yue_pet.png',
  'shadowmem_pet': '/icons/icon_shadowmem_pet.png',
  'shadowmem_minion_pet': '/icons/icon_shadowmem_minion_pet.png',
  'mem_yue_bond': '/icons/icon_mem_yue_bond.png',
  'shadowmem_bond': '/icons/icon_shadowmem_bond.png',
  qjdxy: '/icons/icon_mem_qjdxy.png',
  'tomb-upgrader': '/icons/icon_mem_tomb_upgrader.png',
  corpse: '/icons/icon_mem_corpse.png',
  'shadow-gestalt': '/icons/icon_mem_shadow_gestalt.png',
  soul_wall: '/icons/icon_soul_wall.png',
  dj: '/icons/icon_dj.png',
  djhm: '/icons/icon_djhm.png',
  kyxt: '/icons/icon_kyxt.png',
  hpky: '/icons/icon_hpky.png',
  ghost_fire: '/icons/icon_ghost_fire.png',
  spoil: '/icons/icon_spoil.png',
  mem_corpse_site: '/icons/icon_mem_corpse_site.png',
  ftxd: '/icons/icon_ftxd.png',
  moonaligned: '/icons/icon_moonaligned.png',
  shadowaligned: '/icons/icon_shadowaligned.png',
  tenkibeam: '/icons/icon_tenki_beam.png',
  yuebeam: '/icons/icon_yuebeam.png',
  trap: '/icons/icon_trap.png',
  mem_gestalt_guard: '/icons/icon_mem_gestalt_guard.png',
  stalker_minion: '/icons/icon_stalker_minion.png',
  atk: '/icons/icon_damage.png',
  state: '/icons/icon_state.png',
  shadowseer: '/icons/icon_shadowseer.png',
  command: '/icons/icon_command.png',
  shadowmem_pet_body: '/shadowmem_pet_body.png',
  mem_ruinsnightmare: '/mem_ruinsnightmare.png',
  spoil: '/icons/icon_spoil.png',




  mod: '/icons/icon_mod.png',
  original: '/icons/icon_original.png',
}

// HSL 颜色配置：h (色相), s (饱和度%), l (亮度%)
export const colorMap = {
  health: { h: 0, s: 100, l: 65 },
  sanity: { h: 48, s: 100, l: 60 },
  hunger: { h: 30, s: 100, l: 60 },
  soul: { h: 275, s: 96, l: 75 },
  beast: { h: 46, s: 90, l: 47 },
  ghost: { h: 215, s: 25, l: 65 },
  collar: { h: 189, s: 94, l: 37 },
  'collar-lv2': { h: 189, s: 94, l: 37 },
  'collar-lv3': { h: 189, s: 94, l: 37 },
  'collar-lv4-an': { h: 189, s: 94, l: 37 },
  'collar-lv4-yue': { h: 189, s: 94, l: 37 },
  repair: { h: 142, s: 71, l: 45 },
  hlxz: { h: 25, s: 50, l: 50 },
  mb: { h: 0, s: 0, l: 65 },
  'food-lbnh': { h: 190, s: 70, l: 60 },
  'food-hsmz': { h: 15, s: 80, l: 55 },
  'food-kqm': { h: 35, s: 85, l: 50 },
  'food-rxxcd': { h: 0, s: 85, l: 45 },
  'food-xqs': { h: 45, s: 90, l: 55 },
  yue: { h: 217, s: 55, l: 54 },
  'mem_yue_pet': { h: 195, s: 90, l: 75 },
  'mem_yue_bond': { h: 195, s: 90, l: 75 },
  shadowmem: { h: 280, s: 60, l: 50 },
  shadowmem_minion: { h: 0, s: 0, l: 0 },
  'shadowmem_pet': { h: 280, s: 60, l: 50 },
  shadowmem_minion_pet: { h: 200, s: 2, l: 24 },
  'shadowmem_bond': { h: 280, s: 60, l: 50 },
  qjdxy: { h: 260, s: 30, l: 45 },
  'tomb-upgrader': { h: 258, s: 90, l: 66 },
  corpse: { h: 0, s: 0, l: 55 },
  'shadow-gestalt': { h: 270, s: 50, l: 45 },
  soul_wall: { h: 275, s: 96, l: 75 },
  dj: { h: 340, s: 60, l: 50 },
  djhm: { h: 20, s: 80, l: 50 },
  kyxt: { h: 280, s: 70, l: 60 },
  hpky: { h: 300, s: 80, l: 70 },
  ghost_fire: { h: 180, s: 70, l: 60 },
  spoil: { h: 100, s: 50, l: 40 },
  mem_corpse_site: { h: 30, s: 40, l: 45 },
  ftxd: { h: 0, s: 0, l: 0 },
  moonaligned: { h: 189, s: 97, l: 63 },
  shadowaligned: { h: 358, s: 53, l: 22 },
  shadowseer: { h: 358, s: 53, l: 22 },
  tenkibeam: { h: 228, s: 100, l: 54 },
  yuebeam: { h: 237, s: 100, l: 90 },
  trap: { h: 117, s: 51, l: 82 },
  mem_gestalt_guard: { h: 154, s: 20, l: 47 },
  stalker_minion: { h: 13, s: 17, l: 33 },
  atk: { h: 49, s: 8, l: 59 },
  state: { h: 50, s: 93, l: 60 },
  command: { h: 240, s: 67, l: 72 },
  shadowmem_pet_body: { h: 0, s: 1, l: 36 },
  mem_ruinsnightmare: { h: 358, s: 53, l: 22 },
  spoil: { h: 170, s: 12, l: 47 },


  mod: { h: 199, s: 92, l: 60 },
  original: { h: 40, s: 54, l: 52 },
}
