export const nounMap = {
  '生命值': 'health',
  '饱食度': 'hunger',
  '理智值': 'sanity',
  '精神值': 'sanity',
  '灵魂值': 'soul',
  '灵魂值系统': 'soul',
  '灵魂池': 'hpky',
  '兽化': 'beast',
  '跳跃': 'key',
  '藏食物': 'key',
  '怨灵': 'ghost',
  '尸体': 'corpse',
  '芒头': 'corpse',
  '芒身': 'corpse',
  '芒手': 'corpse',
  '芒腿': 'corpse',
  '芒芒的尸体': 'corpse',
  '封印项圈': 'collar',
  '封印项圈lv1': 'collar',
  '封印项圈lv2': 'collar-lv2',
  '封印项圈lv3': 'collar-lv3',
  '封印项圈lv4·暗': 'collar-lv4-an',
  '暗项圈': 'collar-lv4-an',
  '封印项圈lv4·月': 'collar-lv4-yue',
  '月项圈': 'collar-lv4-yue',
  '芒式修补工具': 'repair',
  '狐狸的凶宅': 'hlxz',
  '芒芒的坟墓': 'mb',
  '芒芒的墓碑': 'mb',
  '凉拌脑花': 'food-lbnh',
  '红烧芒肘': 'food-hsmz',
  '烤全芒': 'food-kqm',
  '热心肠血冻': 'food-rxxcd',
  '星期四特惠套餐': 'food-xqs',
  '食物': 'food',
  '芒伊月': 'yue',
  '荒尹沐': 'shadowmem',
  '友善的芒伊月': 'mem_yue_pet',
  '友善的荒尹沐': 'shadowmem_pet',
  '光辉意志': 'mem_yue_bond',
  '先驱意志': 'shadowmem_bond',
  '被囚禁的虚影': 'qjdxy',
  '被侵蚀的虚影': 'shadow-gestalt',
  '尸体防腐核心': 'tomb-upgrader',
  '芒芒尸体的设计图': 'mem_corpse_site',
  '魂墙(物品)': 'soul_wall',
  '电锯惊魂': 'dj',
  '刻印形态': 'kyxt',
  '电锯轰鸣': "djhm",
  '魂魄刻印': "state",
  '沐尹荒': 'shadowmem_minion',
  '友善的沐尹荒': 'shadowmem_minion_pet',
  '身体(友善的荒尹沐)': 'shadowmem_pet_body',
  '编织梦魇': 'stalker_minion',
  '位面寄生': 'shadowaligned',
  '位面能量': 'shadowaligned',
  '暗影能量': 'shadowaligned',
  '月亮能量': 'moonaligned',
  '暗影位面寄生': 'shadowaligned',
  '月亮位面寄生': 'moonaligned',
  '位面封锁': 'moonaligned',
  '敌意虚影·启迪': 'mem_gestalt_guard',
  '闪耀刻印': 'state',
  '鬼火': 'ghost_fire',
  '月光灼烧': 'state',
  '位面实体降格': 'state',
  '芒伊木': 'mod',
  '芒芒的肢体': 'corpse',
  '启迪陷阱空投仓': 'trap',
  '启迪陷阱空投': 'trap',
  '启迪陷阱': 'trap',
  '启迪陷阱空袭': 'trap',
  '启迪陷阱阵列': 'trap',
  '再一次的机会': 'state',
  '复生虚弱': 'state',
  '灵魂震荡': 'state',
  '灵魂裂痕': 'state',
  '食物中毒': 'state',
  '捕猎姿态': 'beast',
  '分头行动': 'ftxd',
  '意识转移': 'ftxd',
  '死亡回归': 'key',
  '灵魂出窍': 'key',
  '友善随从': 'mod',
  '天基激光': 'tenkibeam',
  '月能激光': 'yuebeam',
  '月能灼烧伤害': 'original',
  '极限催眠': 'original',
  '虚影轰炸区': 'atk',
  '三连击': 'atk',
  '跳劈': 'atk',
  '横扫': 'atk',
  '冲刺': 'atk',
  '劈砍': 'atk',
  '近战反击': 'atk',
  '暗影观察者': 'shadowseer',
  '收回': 'command',
  '战斗': 'command',
  '战斗(友善的荒尹沐)': 'command',
  '工作命令': 'command',
  '解散': 'command',
  '汇合行动(解散)': 'command',
  '分头行动(友善的荒尹沐)': 'command',
  '潜伏恐惧': 'mem_ruinsnightmare',
  '腐烂时间': 'spoil',
  '腐烂速率': 'spoil',
  '最低三维比例': 'mod',
  '灵魂实体专精': 'mem_skill_soul_fire_3',
  '彼世的光芒': 'mem_skill_soul_light',
  '死体精通': 'mem_corpse_mastery',
  '四象离魂': 'mem_skill_soul_split',
  '魂墙(技能)': 'mem_skill_soul_wall',
  '落叶归根': 'mem_skill_instinct_teleport',
  '野兽体质': 'mem_skill_instinct_beastly',
  '易燃易爆': 'mem_explosive_body',
  '逐渐麻木': 'mem_skill_body_numb',
  '精准度“优化”': 'mem_skill_body_precision',
  '参点防腐剂': 'mem_skill_body_preservative',
  '幽灵体质': 'mem_skill_instinct_ghostly',
  '隐藏本能': 'mem_skill_instinct_hide',
  '顷刻炼化': 'mem_skill_soul_hand',
  '休养死息': 'mem_skill_soul_rest',
  '魂魄逸散': 'mem_spirit_link',
  '融魂术': 'mem_skill_soul_melt',
  '本源协调': 'mem_skill_body_medicine',
  '埋葬': 'key',
  '去把这个当目标！': 'key',
  '别捣鼓了，回来！': 'key',
  '启迪强化': 'mod',
  '嘲讽': 'mod',
  '三个灵魂': 'state',
  '无灵魂生物': 'mod',
  '注能消耗': 'mod',
  '暗影负载': 'mod',
  '澎湃心核': 'shadow_heart',
  '永恒心核': 'shadow_heart',
  '月亮装备': 'mod',
};

export const iconMap = {
  health: '/icons/icon_health.webp',
  shadow_heart: '/icons/icon_shadow_heart.webp',
  sanity: '/icons/icon_sanity.webp',
  hunger: '/icons/icon_hunger.webp',
  soul: '/icons/icon_soul.webp',
  beast: '/icons/icon_mem_beast_mode.webp',
  ghost: '/icons/icon_mem_ghost_mode.webp',
  collar: '/icons/icon_mem_xq.webp',
  'collar-lv2': '/icons/icon_mem_xq_lv2.webp',
  'collar-lv3': '/icons/icon_mem_xq_lv3.webp',
  'collar-lv4-an': '/icons/icon_mem_xq_lv4_an.webp',
  'collar-lv4-yue': '/icons/icon_mem_xq_lv4_yue.webp',
  repair: '/icons/icon_mem_repair.webp',
  hlxz: '/icons/icon_mem_hlxz.webp',
  mb: '/icons/icon_mem_mb.webp',
  'food-lbnh': '/icons/icon_mem_food_lbnh.webp',
  'food-hsmz': '/icons/icon_mem_food_hsmz.webp',
  'food-kqm': '/icons/icon_mem_food_kqm.webp',
  'food-rxxcd': '/icons/icon_mem_food_rxxcd.webp',
  'food-xqs': '/icons/icon_mem_food_xqs.webp',
  'food': '/icons/icon_mem_food_xqs.webp',
  yue: '/icons/icon_mem_yue.webp',
  shadowmem: '/icons/icon_shadowmem.webp',
  shadowmem_minion: '/icons/icon_shadowmem_minion.webp',
  'mem_yue_pet': '/icons/icon_mem_yue_pet.webp',
  'shadowmem_pet': '/icons/icon_shadowmem_pet.webp',
  'shadowmem_minion_pet': '/icons/icon_shadowmem_minion_pet.webp',
  'mem_yue_bond': '/icons/icon_mem_yue_bond.webp',
  'shadowmem_bond': '/icons/icon_shadowmem_bond.webp',
  qjdxy: '/icons/icon_mem_qjdxy.webp',
  'tomb-upgrader': '/icons/icon_mem_tomb_upgrader.webp',
  corpse: '/icons/icon_mem_corpse.webp',
  'shadow-gestalt': '/icons/icon_mem_shadow_gestalt.webp',
  soul_wall: '/icons/icon_soul_wall.webp',
  dj: '/icons/icon_dj.webp',
  djhm: '/icons/icon_djhm.webp',
  kyxt: '/icons/icon_kyxt.webp',
  hpky: '/icons/icon_hpky.webp',
  ghost_fire: '/icons/icon_ghost_fire.webp',
  mem_corpse_site: '/icons/icon_mem_corpse_site.webp',
  ftxd: '/icons/icon_ftxd.webp',
  moonaligned: '/icons/icon_moonaligned.webp',
  shadowaligned: '/icons/icon_shadowaligned.webp',
  tenkibeam: '/icons/icon_tenki_beam.webp',
  yuebeam: '/icons/icon_yuebeam.webp',
  trap: '/icons/icon_trap.webp',
  mem_gestalt_guard: '/icons/icon_mem_gestalt_guard.webp',
  stalker_minion: '/icons/icon_stalker_minion.webp',
  atk: '/icons/icon_damage.webp',
  state: '/icons/icon_state.webp',
  shadowseer: '/icons/icon_shadowseer.webp',
  command: '/icons/icon_command.webp',
  shadowmem_pet_body: '/shadowmem_pet_body.webp',
  mem_ruinsnightmare: '/mem_ruinsnightmare.webp',
  spoil: '/icons/icon_spoil.webp',
  mem_skill_soul_fire_3: '/skills/mem_skill_soul_fire_3.webp',
  mem_corpse_mastery: '/skills/mem_corpse_mastery.webp',
  mem_skill_soul_light: '/skills/mem_skill_soul_light.webp',
  key: '/icons/icon_action.webp',
  mem_repair: '/mem_repair-0.webp',
  mem_skill_soul_wall: '/skills/mem_skill_soul_wall.webp',
  mem_skill_soul_split: '/skills/mem_skill_soul_split.webp',
  mem_skill_instinct_teleport: '/skills/mem_skill_instinct_teleport.webp',
  mem_skill_instinct_beastly: '/skills/mem_skill_instinct_beastly.webp',
  mem_explosive_body: '/skills/mem_explosive_body.webp',
  mem_skill_body_numb: '/skills/mem_skill_body_numb_3.webp',
  mem_skill_body_precision: '/skills/mem_skill_body_precision_3.webp',
  mem_skill_body_preservative: '/skills/mem_skill_body_preservative_3.webp',
  mem_skill_instinct_ghostly: '/skills/mem_skill_instinct_ghostly.webp',
  mem_skill_instinct_hide: '/skills/mem_skill_instinct_hide_2.webp',
  mem_skill_soul_hand: '/skills/mem_skill_soul_hand.webp',
  mem_skill_soul_melt: '/skills/mem_skill_soul_melt.webp',
  mem_skill_soul_rest: '/skills/mem_skill_soul_rest_2.webp',
  mem_spirit_link: '/skills/mem_spirit_link.webp',
  mem_skill_body_medicine: '/skills/mem_skill_body_medicine.webp',






  mod: '/icons/icon_mod.webp',
  original: '/icons/icon_original.webp',
}

// HSL 颜色配置：h (色相), s (饱和度%), l (亮度%)
export const colorMap = {
  health: { h: 0, s: 100, l: 65 },
  shadow_heart: { h: 0, s: 100, l: 65 },
  sanity: { h: 48, s: 100, l: 60 },
  hunger: { h: 30, s: 100, l: 60 },
  soul: { h: 275, s: 96, l: 75 },
  beast: { h: 46, s: 90, l: 47 },
  ghost: { h: 215, s: 25, l: 65 },
  collar: { h: 189, s: 94, l: 37 },
  'collar-lv2': { h: 189, s: 94, l: 37 },
  'collar-lv3': { h: 189, s: 94, l: 37 },
  'collar-lv4-an': { h: 189, s: 94, l: 37 },
  'collar-lv4-yue': { h: 189, s: 94, l: 37 },
  repair: { h: 142, s: 71, l: 45 },
  hlxz: { h: 25, s: 50, l: 50 },
  mb: { h: 0, s: 0, l: 65 },
  'food-lbnh': { h: 190, s: 70, l: 60 },
  'food-hsmz': { h: 15, s: 80, l: 55 },
  'food-kqm': { h: 35, s: 85, l: 50 },
  'food-rxxcd': { h: 0, s: 85, l: 45 },
  'food-xqs': { h: 45, s: 90, l: 55 },
  'food': { h: 45, s: 90, l: 55 },
  yue: { h: 217, s: 55, l: 54 },
  'mem_yue_pet': { h: 195, s: 90, l: 75 },
  'mem_yue_bond': { h: 195, s: 90, l: 75 },
  shadowmem: { h: 280, s: 60, l: 50 },
  shadowmem_minion: { h: 0, s: 0, l: 0 },
  'shadowmem_pet': { h: 280, s: 60, l: 50 },
  shadowmem_minion_pet: { h: 200, s: 2, l: 24 },
  'shadowmem_bond': { h: 280, s: 60, l: 50 },
  qjdxy: { h: 260, s: 30, l: 45 },
  'tomb-upgrader': { h: 258, s: 90, l: 66 },
  corpse: { h: 0, s: 0, l: 55 },
  'shadow-gestalt': { h: 270, s: 50, l: 45 },
  soul_wall: { h: 275, s: 96, l: 75 },
  dj: { h: 340, s: 60, l: 50 },
  djhm: { h: 20, s: 80, l: 50 },
  kyxt: { h: 280, s: 70, l: 60 },
  hpky: { h: 300, s: 80, l: 70 },
  ghost_fire: { h: 180, s: 70, l: 60 },
  spoil: { h: 100, s: 50, l: 40 },
  mem_corpse_site: { h: 30, s: 40, l: 45 },
  ftxd: { h: 0, s: 0, l: 0 },
  moonaligned: { h: 189, s: 97, l: 63 },
  shadowaligned: { h: 358, s: 53, l: 22 },
  shadowseer: { h: 358, s: 53, l: 22 },
  tenkibeam: { h: 228, s: 100, l: 54 },
  yuebeam: { h: 237, s: 100, l: 90 },
  trap: { h: 117, s: 51, l: 82 },
  mem_gestalt_guard: { h: 154, s: 20, l: 47 },
  stalker_minion: { h: 13, s: 17, l: 33 },
  atk: { h: 49, s: 8, l: 59 },
  state: { h: 50, s: 93, l: 60 },
  command: { h: 240, s: 67, l: 72 },
  shadowmem_pet_body: { h: 0, s: 1, l: 36 },
  mem_ruinsnightmare: { h: 358, s: 53, l: 22 },
  mem_skill_soul_fire_3: { h: 258, s: 55, l: 45 },
  mem_corpse_mastery: { h: 258, s: 55, l: 45 },
  mem_skill_soul_light: { h: 258, s: 55, l: 45 },
  mem_skill_soul_wall: { h: 258, s: 55, l: 45 },
  mem_skill_soul_split: { h: 258, s: 55, l: 45 },
  mem_skill_instinct_teleport: { h: 258, s: 55, l: 45 },
  mem_skill_instinct_beastly: { h: 258, s: 55, l: 45 },
  mem_explosive_body: { h: 258, s: 55, l: 45 },
  mem_skill_body_numb: { h: 258, s: 55, l: 45 },
  mem_skill_body_precision: { h: 258, s: 55, l: 45 },
  mem_skill_body_preservative: { h: 258, s: 55, l: 45 },
  mem_skill_instinct_ghostly: { h: 258, s: 55, l: 45 },
  mem_skill_instinct_hide: { h: 258, s: 55, l: 45 },
  mem_skill_soul_hand: { h: 258, s: 55, l: 45 },
  mem_skill_soul_melt: { h: 258, s: 55, l: 45 },
  mem_skill_soul_rest: { h: 258, s: 55, l: 45 },
  mem_spirit_link: { h: 258, s: 55, l: 45 },
  mem_skill_body_medicine: { h: 258, s: 55, l: 45 },


  key: { h: 210, s: 90, l: 56 },



  mod: { h: 199, s: 92, l: 60 },
  original: { h: 40, s: 54, l: 52 },
}

export const linkMap = {
  '灵魂值系统': '/mechanics/core.html#def-灵魂值系统',
  '灵魂池': '/mechanics/core.html#def-灵魂池',
  '兽化': '/mechanics/core.html#def-兽化',
  '跳跃': '/mechanics/core.html#def-跳跃',
  '藏食物': '/mechanics/core.html#def-藏食物',
  '怨灵': '/mechanics/core.html#def-怨灵',
  '鬼火': '/mechanics/core.html#def-鬼火',
  '再一次的机会': '/mechanics/core.html#def-再一次的机会',
  '复生虚弱': '/mechanics/core.html#def-复生虚弱',
  '灵魂震荡': '/mechanics/core.html#def-灵魂震荡',
  '灵魂裂痕': '/mechanics/core.html#def-灵魂裂痕',
  '食物中毒': '/mechanics/core.html#def-食物中毒',
  '捕猎姿态': '/mechanics/core.html#def-捕猎姿态',
  '死亡回归': '/mechanics/core.html#def-死亡回归',
  '澎湃心核': '/mechanics/core.html#def-澎湃心核',
  '永恒心核': '/mechanics/core.html#def-永恒心核',
  '暗影观察者': '/mechanics/core.html#def-暗影观察者',
  '灵魂出窍': '/mechanics/core.html#def-灵魂出窍',
  '最低三维比例': '/mechanics/core.html#def-最低三维比例',
  '嘲讽': '/mechanics/core.html#def-嘲讽',
  '芒伊月': '/mechanics/enemies.html#def-芒伊月',
  '荒尹沐': '/mechanics/enemies.html#def-荒尹沐',
  '友善的芒伊月': '/mechanics/enemies.html#def-友善的芒伊月',
  '友善的荒尹沐': '/mechanics/enemies.html#def-友善的荒尹沐',
  '光辉意志': '/mechanics/enemies.html#def-光辉意志',
  '先驱意志': '/mechanics/enemies.html#def-先驱意志',
  '被囚禁的虚影': '/mechanics/enemies.html#def-被囚禁的虚影',
  '被侵蚀的虚影': '/mechanics/enemies.html#def-被侵蚀的虚影',
  '沐尹荒': '/mechanics/enemies.html#def-沐尹荒',
  '友善的沐尹荒': '/mechanics/enemies.html#def-友善的沐尹荒',
  '身体(友善的荒尹沐)': '/mechanics/enemies.html#def-身体(友善的荒尹沐)',
  '编织梦魇': '/mechanics/enemies.html#def-编织梦魇',
  '位面寄生': '/mechanics/enemies.html#def-位面寄生',
  '位面能量': '/mechanics/enemies.html#def-位面能量',
  '暗影能量': '/mechanics/enemies.html#def-暗影能量',
  '月亮能量': '/mechanics/enemies.html#def-月亮能量',
  '暗影位面寄生': '/mechanics/enemies.html#def-暗影位面寄生',
  '月亮位面寄生': '/mechanics/enemies.html#def-月亮位面寄生',
  '位面封锁': '/mechanics/enemies.html#def-位面封锁',
  '敌意虚影·启迪': '/mechanics/enemies.html#def-敌意虚影·启迪',
  '闪耀刻印': '/mechanics/enemies.html#def-闪耀刻印',
  '月光灼烧': '/mechanics/enemies.html#def-月光灼烧',
  '位面实体降格': '/mechanics/enemies.html#def-位面实体降格',
  '启迪陷阱空袭': '/mechanics/enemies.html#def-启迪陷阱空袭',
  '启迪陷阱阵列': '/mechanics/enemies.html#def-启迪陷阱阵列',
  '友善随从': '/mechanics/enemies.html#def-友善随从',
  '天基激光': '/mechanics/enemies.html#def-天基激光',
  '月能激光': '/mechanics/enemies.html#def-月能激光',
  '月能灼烧伤害': '/mechanics/enemies.html#def-月能灼烧伤害',
  '极限催眠': '/mechanics/enemies.html#def-极限催眠',
  '虚影轰炸区': '/mechanics/enemies.html#def-虚影轰炸区',
  '三连击': '/mechanics/enemies.html#def-三连击',
  '跳劈': '/mechanics/enemies.html#def-跳劈',
  '横扫': '/mechanics/enemies.html#def-横扫',
  '冲刺': '/mechanics/enemies.html#def-冲刺',
  '劈砍': '/mechanics/enemies.html#def-劈砍',
  '近战反击': '/mechanics/enemies.html#def-近战反击',
  '收回': '/mechanics/enemies.html#def-收回',
  '战斗': '/mechanics/enemies.html#def-战斗',
  '战斗(友善的荒尹沐)': '/mechanics/enemies.html#def-战斗(友善的荒尹沐)',
  '工作命令': '/mechanics/enemies.html#def-工作命令',
  '解散': '/mechanics/enemies.html#def-解散',
  '潜伏恐惧': '/mechanics/enemies.html#def-潜伏恐惧',
  '启迪强化': '/mechanics/enemies.html#def-启迪强化',
  '三个灵魂': '/mechanics/enemies.html#def-三个灵魂',
  '芒芒的尸体': '/mechanics/items.html#def-芒芒的尸体',
  '封印项圈': '/mechanics/items.html#def-封印项圈',
  '暗项圈': '/mechanics/items.html#def-暗项圈',
  '月项圈': '/mechanics/items.html#def-月项圈',
  '芒式修补工具': '/mechanics/items.html#def-芒式修补工具',
  '狐狸的凶宅': '/mechanics/items.html#def-狐狸的凶宅',
  '芒芒的坟墓': '/mechanics/items.html#def-芒芒的坟墓',
  '凉拌脑花': '/mechanics/items.html#def-凉拌脑花',
  '红烧芒肘': '/mechanics/items.html#def-红烧芒肘',
  '烤全芒': '/mechanics/items.html#def-烤全芒',
  '热心肠血冻': '/mechanics/items.html#def-热心肠血冻',
  '星期四特惠套餐': '/mechanics/items.html#def-星期四特惠套餐',
  '食物': '/mechanics/items.html#def-食物',
  '尸体防腐核心': '/mechanics/items.html#def-尸体防腐核心',
  '芒芒尸体的设计图': '/mechanics/items.html#def-芒芒尸体的设计图',
  '电锯惊魂': '/mechanics/items.html#def-电锯惊魂',
  '刻印形态': '/mechanics/items.html#def-刻印形态',
  '芒芒的肢体': '/mechanics/items.html#def-芒芒的肢体',
  '分头行动': '/mechanics/items.html#def-分头行动',
  '埋葬': '/mechanics/items.html#def-埋葬',
  '别捣鼓了，回来！': '/mechanics/items.html#def-别捣鼓了，回来！',
  '灵魂值': '/mechanics/core.html#def-灵魂值系统',
  '月亮装备': '/mechanics/enemies.html#def-月亮装备',
  '芒手': '/mechanics/items.html#def-芒芒的肢体',
  '芒腿': '/mechanics/items.html#def-芒芒的肢体',
  '芒头': '/mechanics/items.html#def-芒芒的肢体',
  '芒身': '/mechanics/items.html#def-芒芒的肢体',
  '芒芒科技': '/mechanics/items.html#def-狐狸的凶宅',
  '芒芒的墓碑': '/mechanics/items.html#def-芒芒的坟墓',
  '启迪陷阱空投仓': '/mechanics/enemies.html#def-启迪陷阱阵列',
  '启迪陷阱空投': '/mechanics/enemies.html#def-启迪陷阱阵列',
  'W.A.R.B.I.S.盔甲·启迪': '/mechanics/enemies.html#def-启迪强化',
  '月光龙鳞甲·启迪': '/mechanics/enemies.html#def-启迪强化',
  '去把这个当目标！': '/mechanics/items.html#def-分头行动',
  '灵魂实体专精': '/mechanics/skilltree.html#mem_skill_soul_fire_1',
  '彼世的光芒': '/mechanics/skilltree.html#mem_skill_soul_light',
  '死体精通': '/mechanics/skilltree.html#mem_corpse_mastery',
  '魂墙(技能)': '/mechanics/skilltree.html#mem_skill_soul_wall',
  '意识转移': '/mechanics/skilltree.html#mem_spirit_link',
  '四象离魂': '/mechanics/skilltree.html#mem_skill_soul_split',
  '电锯轰鸣': '/mechanics/items.html#def-电锯轰鸣',
  '无灵魂生物': '/mechanics/skilltree.html#mem_skill_soul_hand',
  '注能消耗': '/mechanics/enemies.html#def-注能消耗',
  '暗影负载': '/mechanics/enemies.html#def-暗影负载',
  '魂魄刻印': '/mechanics/items.html#def-魂魄刻印',
  '落叶归根': '/mechanics/skilltree.html#mem_skill_instinct_teleport',
  '野兽体质': '/mechanics/skilltree.html#mem_skill_instinct_beastly',
  '易燃易爆': '/mechanics/skilltree.html#mem_explosive_body',
  '逐渐麻木': '/mechanics/skilltree.html#mem_skill_body_numb_1',
  '精准度“优化”': '/mechanics/skilltree.html#mem_skill_body_precision',
  '参点防腐剂': '/mechanics/skilltree.html#mem_skill_body_preservative_1',
  '幽灵体质': '/mechanics/skilltree.html#mem_skill_instinct_ghostly',
  '隐藏本能': '/mechanics/skilltree.html#mem_skill_instinct_hide_1',
  '顷刻炼化': '/mechanics/skilltree.html#mem_skill_soul_hand',
  '休养死息': '/mechanics/skilltree.html#mem_skill_soul_rest_1',
  '魂魄逸散': '/mechanics/skilltree.html#mem_spirit_link',
  '融魂术': '/mechanics/skilltree.html#mem_skill_soul_melt',
  '本源协调': '/mechanics/skilltree.html#mem_skill_body_medicine',
};

export const officialTerms = [
  'health', 'sanity', 'hunger', 'spoil'
];

export const iconToNounMap = {
  soul: '灵魂值',
  health: '生命值',
  sanity: '理智值',
  hunger: '饱食度',
};


export const aliasMap = {
  '灵魂值': '灵魂值系统',
  '芒手': '芒芒的肢体',
  '芒腿': '芒芒的肢体',
  '芒头': '芒芒的肢体',
  '芒身': '芒芒的肢体',
  '芒芒科技': '狐狸的凶宅',
  '芒芒的墓碑': '芒芒的坟墓',
  '启迪陷阱空投仓': '启迪陷阱阵列',
  '启迪陷阱空投': '启迪陷阱阵列',
  'W.A.R.B.I.S.盔甲·启迪': '启迪强化',
  '月光龙鳞甲·启迪': '启迪强化',
  '去把这个当目标！': '分头行动',
};

export const specialLinks = {
  '灵魂实体专精': '/mechanics/skilltree.html#mem_skill_soul_fire_1',
  '彼世的光芒': '/mechanics/skilltree.html#mem_skill_soul_light',
  '死体精通': '/mechanics/skilltree.html#mem_corpse_mastery',
  '魂墙(技能)': '/mechanics/skilltree.html#mem_skill_soul_wall',
  '意识转移': '/mechanics/skilltree.html#mem_spirit_link',
  '四象离魂': '/mechanics/skilltree.html#mem_skill_soul_split',
  '无灵魂生物': '/mechanics/skilltree.html#mem_skill_soul_hand',
  '落叶归根': '/mechanics/skilltree.html#mem_skill_instinct_teleport',
  '野兽体质': '/mechanics/skilltree.html#mem_skill_instinct_beastly',
  '易燃易爆': '/mechanics/skilltree.html#mem_explosive_body',
  '逐渐麻木': '/mechanics/skilltree.html#mem_skill_body_numb_1',
  '参点防腐剂': '/mechanics/skilltree.html#mem_skill_body_preservative_1',
  '幽灵体质': '/mechanics/skilltree.html#mem_skill_instinct_ghostly',
  '隐藏本能': '/mechanics/skilltree.html#mem_skill_instinct_hide_1',
  '顷刻炼化': '/mechanics/skilltree.html#mem_skill_soul_hand',
  '休养死息': '/mechanics/skilltree.html#mem_skill_soul_rest_1',
  '魂魄逸散': '/mechanics/skilltree.html#mem_spirit_link',
  '融魂术': '/mechanics/skilltree.html#mem_skill_soul_melt',
  '本源协调': '/mechanics/skilltree.html#mem_skill_body_medicine',
  '精准度“优化”': '/mechanics/skilltree.html#mem_skill_body_precision',
};